{% set name = "python-dremio-client" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dremio_client/dremio_client-{{ version }}.tar.gz
  sha256: ff77bc63cb5e3ae50ff14df1834af45c4ac1613779aab8dd06b9392093f512a4

build:
  noarch: python
  number: 1
  entry_points:
    - dremio_client=dremio_client.cli:cli
  script: '{{ PYTHON }} -m pip install . --no-deps -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - click >=6.0
    - requests >=2.21.0
    - confuse
    - pyyaml
    - simplejson
    - attrs
    - six
    - pandas >=0.24.2
    - pyarrow >=0.15.1
    - requests-futures ==1.0.0
    - markdown

test:
  requires:
    - python {{ python_min }}
  imports:
    - dremio_client
    - dremio_client.auth
    - dremio_client.conf
    - dremio_client.flight
    - dremio_client.model
    - dremio_client.util
  commands:
    - dremio_client --help

about:
  home: https://github.com/rymurr/dremio_client
  license: Apache-2.0
  license_file: LICENSE
  summary: Un-official python client for Dremio. See https://dremio.com
  doc_url: https://dremio-client.readthedocs.io/
  dev_url: https://github.com/rymurr/dremio_client

extra:
  recipe-maintainers:
    - harelwa
